server:
  port: 8091
  http2:
    enabled: true
  tomcat:
    basedir: ./var/log
    accesslog:
      enabled: true
      pattern: "%t %a %r %s %{User-Agent}i %H %D"
      rotate: true
  ssl:
    key-store-type: PKCS12
    key-store: classpath:wso2carbon1.jks
    key-store-password: wso2carbon
    key-alias: wso2carbon
security:
  require-ssl: false
#spring:
#  jpa:
#    hibernate:
#    ddl-auto: update
#  datasource:
#    url: jdbc:mysql://localhost:3306/wso2_shared_db
#    username: root
#    password: password
#    driver-class-name: com.mysql.cj.jdbc.Driver
#spring.jpa.show-sql: true
spring:
  profiles:
    active: local
  application:
    name: demo-client
#tomcat:
#  ajp:
#    port: 7091
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
  okhttp:
    enabled: true
  httpclient:
    enabled: false