apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-client
spec:
  selector:
    matchLabels:
      app: demo-client
  template:
    metadata:
      labels:
        app: demo-client
    spec:
      containers:
      - name: demo-client
        image: demo-client:1.0.0
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 8091
---
apiVersion: v1
kind: Service
metadata:
  name: demo-client
spec:
  selector:
    app: demo-client
  ports:
    - port: 8091
      targetPort: 8091
